[package]
name = "xtask"
edition = "2021"
publish = false
version = "0.1.0"

[dependencies]
# This dependency should stay in line with your router version

{{#if integration_test}}
apollo-router-scaffold = { path ="{{integration_test}}apollo-router-scaffold" }
{{else}}
{{#if branch}}
apollo-router-scaffold = { git="https://github.com/apollographql/router.git", branch="{{branch}}" }
{{else}}
apollo-router-scaffold = { git = "https://github.com/apollographql/router.git", tag = "v1.30.1" }
{{/if}}
{{/if}}
anyhow = "1.0.58"
clap = "4.0.32"
