# run a router with this configuration from the project's root directory:
# ./router -c ./examples/propagate-status-code/config.router.yaml -s ./examples/graphql/supergraph.graphql
# You can then open http://localhost:4000 on your browser,
# and try to run a Query and a Mutation in apollo studio.
server:
  cors:
    origins:
      - "https://studio.apollographql.com/"
plugins:
  example.propagate-status-code:
