version: "3.9"
services:

  gateway:
    container_name: apollo-gateway
    build: dockerfiles/federation2-demo/gateway
    environment:
      - APOLLO_OTEL_EXPORTER_TYPE=collector
      - APOLLO_OTEL_EXPORTER_HOST=collector
      - APOLLO_OTEL_EXPORTER_PORT=4318
      - APOLLO_SCHEMA_CONFIG_EMBEDDED=true
    volumes:
      - ./dockerfiles/federation2-demo/supergraph.graphql:/etc/config/supergraph.graphql
    ports:
      - "4100:4000"

  users:
    container_name: users
    build: dockerfiles/federation2-demo/subgraphs/users
    environment:
      - APOLLO_OTEL_EXPORTER_TYPE=collector
      - APOLLO_OTEL_EXPORTER_HOST=collector
      - APOLLO_OTEL_EXPORTER_PORT=4318
    ports:
      - "4001:4000"

  pandas:
    container_name: pandas
    build: dockerfiles/federation2-demo/subgraphs/pandas
    ports:
      - "4002:4000"

  products:
    container_name: products
    build: dockerfiles/federation2-demo/subgraphs/products
    environment:
      - APOLLO_OTEL_EXPORTER_TYPE=collector
      - APOLLO_OTEL_EXPORTER_HOST=collector
      - APOLLO_OTEL_EXPORTER_PORT=4318
    ports:
      - "4003:4000"

  inventory:
    container_name: inventory
    build: dockerfiles/federation2-demo/subgraphs/inventory
    environment:
      - APOLLO_OTEL_EXPORTER_TYPE=collector
      - APOLLO_OTEL_EXPORTER_HOST=collector
      - APOLLO_OTEL_EXPORTER_PORT=4318
    ports:
      - "4004:4000"

  collector:
    container_name: collector
    image: otel/opentelemetry-collector:0.56.0
    command: ["--config=/conf/collector-config.yml"]
    volumes:
      - ./dockerfiles/federation2-demo/opentelemetry/collector-config.yml:/conf/collector-config.yml
    ports:
      - "9464:9464"
      - "4317:4317"
      - "4318:4318"
      - "55679:55679"
    depends_on:
      - zipkin

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:2.23.18
    ports:
      - "9411:9411"
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.36.2
    volumes:
      - ./dockerfiles/federation2-demo/opentelemetry/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
