version: "3.9"
services:

  apollo-router:
    container_name: apollo-router
    image: ghcr.io/apollographql/router:v1.30.1
    volumes:
      - ./supergraph.graphql:/etc/config/supergraph.graphql
      - ./router/datadog.router.yaml:/etc/config/configuration.yaml
    command:
      [
        "-c",
        "/etc/config/configuration.yaml",
        "-s",
        "/etc/config/supergraph.graphql",
        "--log",
        "info"
      ]
    ports:
      - 4000:4000
    depends_on:
      - datadog-agent

  subgraph:
    build: datadog-subgraph
    ports:
      - 4001:4001
    environment:
      - DD_SERVICE=accounts
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_AGENT_PORT=8126
    depends_on:
      - datadog-agent

  datadog-agent:
    image: gcr.io/datadoghq/agent
    ports:
      - 4317:4317
    environment:
      - DD_API_KEY
