[package]
name = "jwt-auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1.0.55"
apollo-router = { path = "../../apollo-router" }
apollo-router-core = { path = "../../apollo-router-core" }
async-trait = "0.1.53"
hex = "0.4.3"
http = "0.2.6"
jwt-simple = "0.10.8"
schemars = "0.8.8"
serde = "1.0.136"
serde_json = "1.0.79"
strum = { version = "0.24.0", features = ["derive"] }
strum_macros = "0.24.0"
tokio = { version = "1.17.0", features = ["full"] }
tower = { version = "0.4.12", features = ["full"] }
