[package]
name = "supergraph_sdl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1"
apollo-compiler = "0.3.0"
apollo-parser = "0.3.2"
apollo-router = { path = "../../../apollo-router" }
async-trait = "0.1"
futures = "0.3"
http = "0.2"
once_cell = "1.13.0"
tower = { version = "0.4", features = ["full"] }
tracing = "0.1"
