[package]
name = "compose-your-graphql-router"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.55"
apollo-router = { path = "../../apollo-router" }
apollo-router-core = { path = "../../apollo-router-core" }
serde_json = "1.0.79"
tokio = { version = "1.17.0", features = ["full"] }
tower = "0.4.12"
tracing-subscriber = { version = "0.3.9", features = ["json", "env-filter"] }
