server:
  listen: 127.0.0.1:4000
plugins:
  apollo.reporting:
    spaceport:
      # By default, Apollo Router runs an internal collector. You can override
      # this default behavior by setting `external: true`. If `true`, no reporting
      # agent spawns, and the router instead communicates with `collector` below.
      external: false

      # If `external` is `true`, this should be the location of a spaceport
      # that's running external from the Router. Omit otherwise.
      collector: https://127.0.0.1:50051

      # If `external` is `false`, this is the interface and port to listen on.
      # Omit otherwise.
      listener: 127.0.0.1:50051
