[package]
name = "execution"
version = "0.1.0"
authors = ["bryncooke <bryncooke@gmail.com>"]
edition = "2018"
license-file = "./LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
query-planner = { path = "../query-planner" }