{{- if .Values.router.configuration }}
{{- $routerFullName := include "router.fullname" .  -}}
{{- $configuration := dict "telemetry" (dict "metrics" (dict "common" (dict "resources" (dict "service.name" $routerFullName)))) -}}
{{- $_ := mustMergeOverwrite $configuration .Values.router.configuration  -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $routerFullName }}
  labels:
    {{- include "router.labels" . | nindent 4 }}
    {{- if .Values.extraLabels }}
    {{- include "common.templatizeExtraLabels" . | trim | nindent 4 }}
    {{- end }}
data:
  configuration.yaml: |
    {{- toYaml $configuration | nindent 4 }}
{{- end }}
