{{- if .Values.virtualservice.enabled -}}
{{- $fullName := include "router.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $hostName := printf "%s.%s.svc.cluster.local" $fullName .Release.Namespace }}

{{ if .Values.virtualservice.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.virtualservice.namespace }}
  labels:
    {{- include "router.labels" . | nindent 4 }}
    {{- if .Values.extraLabels }}
    {{- include "apollographql.templatizeExtraLabels" . | trim | nindent 4 }}
    {{- end }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hosts:
  - "*"
  {{- if .Values.virtualservice.gatewayName }}
  gateways:
  - {{ .Values.virtualservice.gatewayName }}
  {{- else if .Values.virtualservice.gatewayNames }}
  gateways:
    {{- toYaml .Values.virtualservice.gatewayNames | nindent 4 }}
  {{- end }}
  {{- if .Values.virtualservice.http }}
  http:
  {{- if .Values.virtualservice.http.main.enabled }}
    - name: "router-graphql-routes"
      match:
        - uri:
            prefix: "/graphql"
        - uri:
            exact: "/"
      route:
        - destination:
            host: {{ $hostName }}
            port:
              number: 80
  {{- end }}
  {{- if .Values.virtualservice.http.additionals }}
    {{- toYaml .Values.virtualservice.http.additionals | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
