# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "{{name}}"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["xtask"]

[[bin]]
name = "router"
path = "src/main.rs"

[dependencies]

{{#if integration_test}}
{{else}}
{{#if branch}}
{{else}}
anyhow = "1.0.58"
apollo-router = { path = "{{integration_test}}apollo-router" }
apollo-router = { git = "https://github.com/apollographql/router.git", branch = "{{branch}}" }
# Note if you update these dependencies then also update xtask/Cargo.toml

{{/if}}
{{/if}}
apollo-router = "2.0.0-alpha.7"
async-trait = "0.1.52"
schemars = "0.8.10"
serde = "1.0.149"
serde_json = "1.0.79"
tokio = { version = "1.17.0", features = ["full"] }
tower = { version = "0.4.12", features = ["full"] }
tracing = "0.1.37"

# this makes build scripts and proc macros faster to compile
[profile.dev.build-override]
strip = "debuginfo"
incremental = false
