[package]
name = "apollo-uplink"
version = "0.1.0-preview.2"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.21"
graphql_client = "0.10.0"
reqwest = { version = "0.11.10", features = ["json"] }
serde = { version = "1.0.136", features = ["derive", "rc"] }
tokio = "1.17.0"
tokio-stream = "0.1.8"
tracing = "0.1.32"
url = "2.2.2"

[build-dependencies]
rover-client = {git = "https://github.com/apollographql/rover.git", rev="c650649682ab891a3b718b5277c3b2e9a5fc5224"}
reqwest = { version = "0.11.10" }

[dev-dependencies]
tokio = { version = "1.17.0", default-features = false, features = ["macros", "rt-multi-thread"] }
