[package]
name = "everything-subgraph"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.20"
async-graphql = "7"
async-graphql-axum = "6"
env_logger = "0.11"
tokio = { version = "1.22.0", features = ["time", "full"] }
tower = "0.4.0"
