[package]
name = "external-subgraph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1"
apollo-router = { path = "../../../apollo-router" }
async-trait = "0.1"
futures = "0.3"
http = "0.2.8"
hyper = "0.14.23"
multimap = "0.9.0"
schemars = { version = "0.8", features = ["url"] }
serde = "1"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tower = { version = "0.4", features = ["full"] }
tracing = "0.1"
