name: Update Apollo Protobuf
run-name: ${{ github.actor }} is updating the Apollo Protobuf ðŸš€
on:
  workflow_dispatch:
  schedule:
    # On the 5 of every hour
    - cron:  '5 * * * *'
jobs:
  Update-Protobuf-Schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Make changes to pull request
        run: |
          curl -f https://usage-reporting.api.apollographql.com/proto/reports.proto > ./apollo-router/src/plugins/telemetry/proto/reports.proto
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update Apollo Protobuf schema
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: create-pull-request/apollo-proto-updates
          team-reviewers: |
            router
          add-paths: |
            apollo-router/src/plugins/telemetry/proto/reports.proto
          delete-branch: true
          title: 'chore: Update Apollo Protobuf'
          body: |
            This updates the copy of `reports.proto` which this repository relies on with the latest copy fetched via our public endpoint.

            > [!IMPORTANT]
            > This PR will be continuously force-pushed with the new `reports.proto` copy. If the update requires code changes, apply them
            > in a separate PR. This PR will be automatically closed if it is no longer necessary.
