[tools]
rust = "1.88.0"
"aqua:cargo-bins/cargo-binstall" = "1.12.3"
"cargo:cargo-nextest" = "0.9.70"
"cargo:cargo-deny" = "0.14.21"
"cargo:cargo-edit" = "0.12.2"
"cargo:cargo-about" = "0.6.6"
"cargo:cargo-insta" = "1.38.0"
"cargo:htmlq" = "0.4.0"
"cargo:cargo-watch" = "8.5.3"
"cargo:typos-cli" = "1.31.1"
protoc = "21.8"
gh = "2.72.0"
helm = "3.17.3"
helm-docs = "1.14.2"
yq = "4.45.1"
jq = "1.7.1"
