[tools]
# renovate-automation: rustc version
rust = "1.91.1"
"aqua:cargo-bins/cargo-binstall" = "1.16.2"
"cargo:cargo-nextest" = "0.9.70"
"cargo:cargo-deny" = "0.18.2"
"cargo:cargo-edit" = "0.13.0"
"cargo:cargo-about" = "0.8.0"
"cargo:cargo-insta" = "1.38.0"
"cargo:htmlq" = "0.4.0"
"cargo:cargo-watch" = "8.5.3"
"cargo:cargo-machete" = "0.9.0"
"cargo:typos-cli" = "1.31.1"
protoc = "33.1"
gh = "2.72.0"
helm = "3.19.2"
helm-docs = "1.14.2"
yq = "4.48.2"
jq = "1.8.1"
redis = "7.4.7"
