[tools]
# renovate-automation: rustc version
rust = { version = "1.90.0", targets = "x86_64-apple-darwin,aarch64-apple-darwin", profile = "default", components = "llvm-tools" }
"cargo:cargo-llvm-cov" = "0.6.16"
"ubi:codecov/codecov-cli" = "10.4.0"
